name: Build and Test

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # Checkout PR
      - uses: actions/checkout@v2

      # Load Cached Node Modules
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Use Node 12.x
      - name: Use Node 12.x
        uses: docker://node:12-slim

      # Install, build and test
      - name: Install, build and test
        run: yarn install && yarn build && yarn test && yarn lint
