name: Continuous Integration

on:
  push:
    branches: [dev, qa, staging, main]

# Initializes environment variables for the workflow
env:
  AWS_DEFAULT_REGION: us-east-1 # Deployment Region

jobs:
  dev:
    name: Deploy to dev and feature branch builds
    if: github.ref == 'refs/heads/dev' || contains(github.ref, 'refs/heads/myf-')
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: export CLOUDFRONT_DISTRIBUTION_ID
        run: echo "CLOUDFRONT_DISTRIBUTION_ID=$(aws ssm get-parameters  --names /myfile/dev/cloudfront-distribution-id | jq '.Parameters[0].Value' | tr -d \")" >> $GITHUB_ENV
      - name: export UI_BUCKETNAME
        run: echo "UI_BUCKETNAME=$(aws ssm get-parameters  --names /myfile/dev/ui-bucketname | jq '.Parameters[0].Value' | tr -d \")" >> $GITHUB_ENV
      - uses: ./.github/actions/ui
        with:
          git_branch_env: ${GITHUB_REF##*/}
          s3_bucket: ${{ env.UI_BUCKETNAME }}
          s3_bucket_region: ${{ env.AWS_DEFAULT_REGION }}
          cloudfront_distribution_id: ${{ env.CLOUDFRONT_DISTRIBUTION_ID }}
  staging:
    name: Deploy to Staging
    if: github.ref == 'refs/heads/stage'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: export CLOUDFRONT_DISTRIBUTION_ID
        run: echo "CLOUDFRONT_DISTRIBUTION_ID=$(aws ssm get-parameters  --names /myfile/staging/cloudfront-distribution-id | jq '.Parameters[0].Value' | tr -d \")" >> $GITHUB_ENV
      - name: export UI_BUCKETNAME
        run: echo "UI_BUCKETNAME=$(aws ssm get-parameters  --names /myfile/staging/ui-bucketname | jq '.Parameters[0].Value' | tr -d \")" >> $GITHUB_ENV
      - uses: ./.github/actions/ui
        with:
          git_branch_env: ${GITHUB_REF##*/}
          s3_bucket: ${{ env.UI_BUCKETNAME }}
          s3_bucket_region: ${{ env.AWS_DEFAULT_REGION }}
          cloudfront_distribution_id: ${{ env.CLOUDFRONT_DISTRIBUTION_ID }}
  prod:
    name: Deploy to Prod
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: export CLOUDFRONT_DISTRIBUTION_ID
        run: echo "CLOUDFRONT_DISTRIBUTION_ID=$(aws ssm get-parameters  --names /myfile/prod/cloudfront-distribution-id | jq '.Parameters[0].Value' | tr -d \")" >> $GITHUB_ENV
      - name: export UI_BUCKETNAME
        run: echo "UI_BUCKETNAME=$(aws ssm get-parameters  --names /myfile/prod/ui-bucketname | jq '.Parameters[0].Value' | tr -d \")" >> $GITHUB_ENV
      - uses: ./.github/actions/ui
        with:
          git_branch_env: prod
          s3_bucket: ${{ env.UI_BUCKETNAME }}
          s3_bucket_region: ${{ env.AWS_DEFAULT_REGION }}
          cloudfront_distribution_id: ${{ env.CLOUDFRONT_DISTRIBUTION_ID }}
