name: Push to S3

on:
  push:
    branches: [master]

jobs:
  build:
    name: Push to S3
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2

      # Create Archive
      - name: Create Archive
        env:
          PIPELINE_CONFIG: ${{ secrets.PIPELINE_CONFIG }}
          CDK_CONTEXT: ${{ secrets.CDK_CONTEXT }}
        run: |
          MESSAGE=$(git show -s --format=%B $GITHUB_SHA | head -n 1 | sed 's/"/\\"/g')
          echo -n "{\"buildNumber\":\"$GITHUB_RUN_NUMBER\", \"file\":\"builds/${GITHUB_RUN_NUMBER}-build.zip\", \"commit\": \"$GITHUB_SHA\", \"message\": \"$MESSAGE\"}" > build-details.json
          echo $PIPELINE_CONFIG > packages/infra/cdk.pipeline.json
          echo $CDK_CONTEXT > packages/infra/cdk.context.json
          git archive --format zip -o archive.zip HEAD
          zip -ur archive.zip build-details.json
          zip -ur archive.zip packages/infra/cdk.pipeline.json
          zip -ur archive.zip packages/infra/cdk.context.json
          mv archive.zip ${GITHUB_RUN_NUMBER}-build.zip
          ls -la

      # Upload Archive
      - name: Upload Archive
        run: |
          aws s3 cp ${GITHUB_RUN_NUMBER}-build.zip s3://${{ secrets.AWS_S3_BUCKET }}/builds/${GITHUB_RUN_NUMBER}-build.zip
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
